### ISSUE TITLE
STK

### ISSUE THREAD

**Issue by patinhas19** [supertuxkart/stk-code#2638]
The game super tux kart to start gives error.

**Comment by auriamg** [comment]
We will need more information, like what is your OS, which version of STK, and what is the error

**Comment by patinhas19** [comment]
My operating system is Windows 7.
RAM is 4GB.
64 bits.
And the error when starting supertux kart is:

---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 BaseThreadInitThunk
 RtlInitializeExceptionChain
 RtlInitializeExceptionChain
---------------------------
OK   
---------------------------

**Comment by patinhas19** [comment]
The version Super Tux Kart is 0.9.2

**Comment by hiker** [comment]
Can you paste the log file  %APPDATA%/supertuxkart/0.8.2/stdout.log (you can enter it like this in the explorer) here?

**Comment by patinhas19** [comment]
The text stdout is the following:


[error  ] UserConfig: Could not read user config file 'C:\Users\Jojo\AppData\Roaming/supertuxkart/0.8.2/config.xml'.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is 'C:\Users\Jojo\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\Jojo\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\Jojo\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\Jojo\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from 'data/po/'.
[verbose  ] translation: GetLocaleInfo langname returns 'pt'.
[verbose  ] translation: GetLocaleInfo tryname returns 'PT'.
[verbose  ] translation: Env var LANGUAGE = 'pt_PT'.
[verbose  ] translation: Language 'Portuguese (Portugal)'.
[info   ] IrrDriver: OpenGL version: 3.1
[info   ] IrrDriver: OpenGL vendor: ATI Technologies Inc.
[info   ] IrrDriver: OpenGL renderer: ATI Mobility Radeon HD 3400 Series
[info   ] IrrDriver: OpenGL version string: 3.1.8787 BETA
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] irr_driver: GLSL supported.
[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[warn   ] [IrrDriver Temp Logger]: Level 3: GLSL shader failed to compile

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader failed to compile with the following errors:
ERROR: 0:2: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.


[error  ] shaders: Shader NORMAL_MAP failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader NORMAL_MAP_LIGHTMAP failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader SKYBOX failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader SPLATTING failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader WATER failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader WATER_SURFACE failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader SPHERE_MAP failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader GRASS failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader GRASS_REF failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader MOTIONBLUR failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader GAUSSIAN3H failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader GAUSSIAN3V failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader OBJECT_UNLIT failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader OBJECTPASS failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader OBJECTPASS_REF failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader OBJECTPASS_RIMLIT failed to load. Update your drivers, if the issue persists, report a bug to us.
[error  ] shaders: Shader DISPLACE failed to load. Update your drivers, if the issue persists, report a bug to us.
[info   ] Freetype Environment: Loading fonts...
[info   ] Freetype Environment: DPI for Normal Font is 21.
[info   ] Freetype Environment: DPI for Title Font is 36.
[info   ] Freetype Environment: DPI for Digit Font is 32.
[info   ] ScalableFont::loadTTF: Created 15 glyphs supporting 16 characters for high-res digits font Sigmar using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 93 glyphs supporting 150 characters for bold title font Ubuntu using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu using 1 glyph page(s).
[info   ] shader: Compiling shader : texturedquad.vert
[error  ] GLWrap: Error in shader texturedquad.vert
[error  ] GLWrap: Vertex shader failed to compile with the following errors:
ERROR: 0:1: '' :  Version number not supported by GL2
ERROR:  compilation errors.  No code generated.

[info   ] shader: Compiling shader : texturedquad.frag
[error  ] GLWrap: Error in shader texturedquad.frag
[error  ] GLWrap: Fragment shader failed to compile with the following errors:
ERROR: 0:1: '' :  Version number not supported by GL2
WARNING: 0:5: '' : Keyword 'precision' is supported in GLSL 1.3 
ERROR:  compilation errors.  No code generated.

[error  ] GLWrapp: Error when linking these shaders :
[error  ] shader: texturedquad.vert
[error  ] shader: texturedquad.frag
[error  ] GLWrapp: Vertex and Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed.

**Comment by auriamg** [comment]
Hi, you appear to be using a Radeon HD 3400 GPU, which does not meet our minimal requirements : this GPU was released in 2007/2008 (8-9 years ago!) and is not powerful enough to run modern games I'm afraid. Maybe you can stick to older version of STK as it is unlikely we can get the game in its current state running on older/less powerful GPUs (our minimum requirement is intel HD 3000 or equivalent)

**Comment by deveee** [comment]
It is this nasty radeon drivers version which says that it supports OpenGL 3.1, but it doesn't support GLSL 1.4. See: https://github.com/supertuxkart/stk-code/issues/2449

I fixed it some time ago in STK git version. Note that I added graphics restriction to all drivers versions <= 3.1.8787. You can check if it occurs also with newer drivers, because I don't have such possibility.

As a workaround for now, you can set ```force_legacy_device``` parameter to ```true``` in config.xml file. It can be found in %appdata%\supertuxkart\0.8.2.

**Comment by qwertychouskie** [comment]
The drivers for your card can be found here: http://support.amd.com/en-us/download/desktop/legacy?product=legacy2&os=Windows%207%20-%2064

This driver will fix the crash, but most likely it will still not work right: https://github.com/supertuxkart/stk-code/issues/2521 (the All-in-Wonder HD is basically the Radeon HD 3650, which should be better than yours, but still doesn't work...)

**Comment by patinhas19** [comment]
changed the force_legacy_device parâmetro cofing.xml file to true, the
game worked. thanks for listening.


2016-09-28 7:05 GMT+01:00 Deve <notifications@github.com>:
