### ISSUE TITLE
Game crashes on Zen Garden challenge

### ISSUE THREAD

**Issue by pfred1** [supertuxkart/stk-code#3280]
## Description
In story mode when I try to run the Zen Challenge the game crashes before the race starts. Like right at Go. As in I can sit at the line then before I can go the game just segfaults out. Never a good thing.
Provide a description of your issue.
For any suggestions, please address them on the [forum](https://forum.freegamedev.net/viewforum.php?f=16).

## Steps to reproduce
I take the Zen Garden challenge
## Configuration

STK release version:
Hard to say ./supertuxkart -v just tells me
[info   ] main: SuperTuxKart, git.
But the date of the binary is  May 30 if that helps any.
STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:
git clone https://github.com/supertuxkart/stk-code stk-code
System: 
Debian Stretch
Graphics card: 
 NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)

CPU: 
Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz

Gamepads/keyboards models if related to the issue:

## Additional information

Please provide stdout.log, it is located in

* %appdata%\supertuxkart\0.8.2 (windows)
* ~/Library/Application Support/supertuxkart/0.8.2 (mac)
* $XDG_CONFIG_HOME/supertuxkart/0.8.2 or ~/.config/supertuxkart/0.8.2 (linux, and other unix based systems)

stdout.log
```pfred1@five:~/Build/STK/stk-code/build/bin$ cat /home/pfred1/.config/supertuxkart/0.8.2/stdout.log
[info   ] [FileManager]: Data files will be fetched from: '../../data/'
[info   ] [FileManager]: Data files will be fetched from: '../../data/../../stk-assets/'
[info   ] [FileManager]: User directory is '/home/pfred1/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/pfred1/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/pfred1/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/pfred1/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../../data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../../data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../../data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.UTF-8'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] tinygettext: Adding language fallback en

[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: GeForce GTX 750 Ti/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 375.82
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_normal_visualizer.frag
[info   ] irr_driver: GLSL supported.
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/colortexturedquad.frag
[info   ] HTTPRequest: Sending userid=90348&token=************************ to https://addons.supertuxkart.net/api/v2/user/saved-session/
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
[info   ] addons: Using cached addons.xml.
[info   ] HTTPRequest: Downloading https://addons.supertuxkart.net/dl/images/32999604857af930517f49.png
[info   ] GrandPrixManager: Loading Grand Prix files from ../../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/pfred1/.local/share/supertuxkart/grandprix/
[info   ] Achievements: Synching achievement 1,2,3,4,7,8,9,11 to server.
[info   ] HTTPRequest: Sending userid=90348&token=************************&achievementid=1%2C2%2C3%2C4%2C7%2C8%2C9%2C11 to https://addons.supertuxkart.net/api/v2/user/achieving/
[info   ] HTTPRequest: Sending userid=90348&token=************************&visitingid=90348 to https://addons.supertuxkart.net/api/v2/user/get-friends-list/
[info   ] HTTPRequest: Sending userid=90348&token=************************ to https://addons.supertuxkart.net/api/v2/user/poll/
[verbose  ] RaceManager: Nb of karts=1, ghost karts:0 ai:0 players:1

[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-assets/tracks/overworld/splatting.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/degraded_ibl.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sunlight.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/pointlight.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/pointlight.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/combine_diffuse_color.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/glow.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/tonemap.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/mlaa_color1.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/mlaa_blend2.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/mlaa_neigh3.frag
[info   ] Script: allchallenges: unlocked_challenges=16, challenges=26
[info   ] Script: allchallenges: unlocked_challenges=16, challenges=26
[info   ] Script: allchallenges: unlocked_challenges=16, challenges=26
[info   ] Script: allchallenges: unlocked_challenges=16, challenges=26
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/importance_sampling_specular.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/IBL.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/pointlightscatter.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/gaussian6v.comp
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/gaussian6h.comp
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sky.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sky.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/simple_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/simple_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/sp_text_billboard.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/passthrough.frag
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 41
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/coloredquad.frag
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[verbose  ] RaceManager: Nb of karts=2, ghost karts:0 ai:1 players:1

[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/godfade.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/gaussian3v.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/gaussian3h.frag
[info   ] ShaderFilesManager: Compiling shader: /home/pfred1/Build/STK/stk-code/data/shaders/godray.frag
pfred1@five:~/Build/STK/stk-code/build/bin$ 

pfred1@five:~/Build/STK/stk-code/build/bin$ 

```

If your issue is related to the input config (gamepads, keyboards), please provide your file input.xml located in the same directory as stdout.log.

input.xml
```xml

```

If an error message was shown, please copy paste the complete error message or a screenshot of it.
let me make it do it again
error
Segmentation fault

I should add that I ran that track on another challenge (one of the grand prix) and it worked fine. So it is something with that particular Zen Garden challenge. Maybe the AI of the driver? Is my guess.

On older builds I never had any problems whatsoever. I was able to complete all of the challenges. The game always ran just fine for me. It just happened with this latest git build. So I doubt it is what I am doing. But who knows?

```

```

**Comment by auriamg** [comment]
In any case, do you feel comfortable running stk in gdb to get us some information, assuming this is linux?

```
gdb supertuxkart
run
```

... make it crash ...

```
bt
```

**Comment by Alayan-stk-2** [comment]
Can't reproduce on my side, additional details on config and steps are needed (the aforementioned backtrace would be ideal)

**Comment by pfred1** [comment]
Software debugging is beyond my pay grade. But this is what gdb said when I ran supertuxkart in it

supertuxkart: /home/pfred1/Build/STK/stk-code/src/karts/controller/skidding_ai.cpp:2022: void SkiddingAI::computeNearestKarts(): Assertion `target_index >= 0 && target_index <= n-1' failed.

Thread 1 "supertuxkart" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) Exception ignored in: <gdb.GdbOutputFile object at 0x7f0b37b2e630>
Traceback (most recent call last):
  File "/usr/share/gdb/python/gdb/__init__.py", line 43, in flush
    def flush(self):
KeyboardInterrupt

I ran a strace too if anyone is interested in that I can attach it. It is 43MB though. I guess I could zip it up? Bzipped it is 2MB. Hopefully this little snippet is all anyone needs though.

**Comment by auriamg** [comment]
Thank you, this is the important part here :
```
supertuxkart: /home/pfred1/Build/STK/stk-code/src/karts/controller/skidding_ai.cpp:2022: void SkiddingAI::computeNearestKarts(): Assertion `target_index >= 0 && target_index <= n-1' failed.
```

this line of code no longer exists in the latest development version, so this bug should be fixed in next version

**Comment by pfred1** [comment]
K thanks I'll git pull a newer tree and build that.

**Comment by pfred1** [comment]
I just cloned a new tree and built it now gdb says:

Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
0x0000555555a8b9cc in SkiddingAI::computeNearestKarts() ()
(gdb) Exception ignored in: <gdb.GdbOutputFile object at 0x7f4b25476630>

and the game still crashes. Should I open up a new ticket or will this one suffice?

**Comment by Alayan-stk-2** [comment]
I found the issue by looking at the function, it is a trivial fix. The crashing code line still exists in the current version ; but a ctrl+F for "assert(" wouldn't have found it, as there is a space before the parenthesis.

**Comment by pfred1** [comment]
If it is fixed and I can complete my Zen Challenge I'm happy. I'll pull a new tree tonight and build it. That should work now, right?
