### ISSUE TITLE
Crashes in some arenas for debug-builds

### ISSUE THREAD

**Issue by v1993** [supertuxkart/stk-code#5536]
### Description

Trying to start a battle in the (featured) add-on "Moria's Race City Arena" with 5+ players (e.g. 4+ AI players) leads to a crash from out-of-bounds access. Crash happens after the arena loads and begins to render but before much has a chance to happen.

### Steps to reproduce

1. Launch STK
2. Install the arena "Moria's Race City Arena"
3. Start a battle in that arena with 4 or more AI karts

### Configuration

* SuperTuxKart version: 1.5
* Installed from official CachyOS repositories
* AMD Ryzen 7 7735HS + Nvidia 4060 Max-Q

### Error message

```
/usr/include/c++/15.2.1/bits/stl_bvector.h:1158: std::vector<bool, _Alloc>::reference std::vector<bool, _Alloc>::operator[](size_type) [with _Alloc = std::allocator<bool>; reference = std::vector<bool>::reference; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 1 "supertuxkart" received signal SIGABRT, Aborted.
```

### Log File (stdout.log)

```
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/eri/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/eri/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/eri/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/eri/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/share/supertuxkart/data/tracks/'.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Compiled SDL Version 2.32.56
[info   ] [IrrDriver Logger]: Current SDL Version 2.32.56
[info   ] [IrrDriver Logger]: Using renderer: OpenGL 4.3.0
[info   ] [IrrDriver Logger]: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2: NVIDIA Corporation
[info   ] [IrrDriver Logger]: OpenGL driver version is 1.2 or better.
[info   ] [IrrDriver Logger]: GLSL version: 4.3
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 580.95.05
[info   ] IrrDriver: OpenGL total memory: 8188
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 2048
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] GUI: Loading skin data from file: /usr/share/supertuxkart/data/skins/classic/stkskin.xml
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_displace_ssr.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.frag
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[error  ] SFXBuffer: Positional audio is not supported with stereo files, but /usr/share/supertuxkart/data/sfx/WilhelmScream.ogg is stereo
[error  ] SFXBuffer: Positional audio is not supported with stereo files, but /usr/share/supertuxkart/data/sfx/car_revup.ogg is stereo
[warn   ] track: Music information file 'amazon_jungle.music' not found for track 'Amazonian Journey' - ignored.

[warn   ] track: Music information for track 'Amazonian Journey' replaced by default music.

[warn   ] track: Music information file 'extreme.music' not found for track 'Extreme playground stadium' - ignored.

[warn   ] track: Music information for track 'Extreme playground stadium' replaced by default music.

[warn   ] Track: NavMesh is not found for arena STK Mercury, disable AI for it.

[info   ] addons: Using cached addons.xml.
[info   ] GrandPrixManager: Loading Grand Prix files from /usr/share/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/eri/.local/share/supertuxkart/grandprix/
[warn   ] Material: Missing container id for gnu_accessories.png, no texture compression for it will be done.
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] Material: Missing container id for Pepper_lamp_diff.png, no texture compression for it will be done.
[info   ] HTTPRequest: Downloading https://discord.com/api/v8/oauth2/applications/817760324983324753/assets
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/linearizedepth.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/ssao.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bilateralH.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bilateralV.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/degraded_ibl.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sunlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/combine_diffuse_color.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/glow.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/tonemap.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_color1.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_blend2.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_neigh3.frag
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget ai-blue-spinner of type 1 has no dimensions
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget ai-blue-text of type 5 has no dimensions
[verbose  ] RaceManager: Nb of karts=5, ghost karts:0 ai:4 players:1

[warn   ] material: Unknown node type 'material' for texture 'track__shine_yello.png' - ignored.
[info   ] Track: Overall scene complexity estimated at 678, Auto-LoD multiplier is 1.359659
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/importance_sampling_specular.frag
[info   ] ThreeStrikesBattle: 4 spare tire kart(s) created.
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/IBL.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sunlightshadowpcss.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/passthrough.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6v.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6h.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6h.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bloomblend.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/lensblend.frag
```

**Comment by CrystalDaEevee** [comment]
The arena supports up to 17 karts but the max-arena-players string is set to 18, trying to play with 18 karts will cause the game to crash. This is easily solvable by the Add-on author

**Comment by v1993** [comment]
It crashes with as few as 5 karts, far below that limit. I've also encountered this crash with a few other add-on arenas.

**Comment by CrystalDaEevee** [comment]
Are you using the Debug build of the game? It doesn't happen with the Release builds

**Comment by Alayan-stk-2** [comment]
There were two separate issues here:
- Some arenas have start positions that are not valid rescue positions. This doesn't matter too much for actual gameplay as far as I can tell, but it triggered an assert.
- If the total of spare tire karts + normal karts spawned exceeded the game's maximum number of karts (20 by default), another assert would be failed. In the past, this could not happen because battle mode had 10 karts maximum.

**Comment by v1993** [comment]
I'm using a build with whatever flags Arch is using by default, i.e. certainly not intended to be debug. This error is most likely triggered by the `-Wp,-D_GLIBCXX_ASSERTIONS` or `-Wp,-D_FORTIFY_SOURCE=3` g++ options , probably the first one.

**Comment by Alayan-stk-2** [comment]
When an assert fails, it crashes the game in order to make the problem immediately noticeable instead of keeping it subtle. Typically asserts are used to confirm that some variable is properly defined or within an expected range, where deviation indicates a bug that should be fixed.

It's useful for development and testing, but to just play the game normally, asserts should not be enabled.

**Comment by v1993** [comment]
Thank you for fixing this!

FWIW, the asserts in question are intended as a security hardening measure and have been enabled on Fedora and Arch for a while; other distributions, [e.g. Gentoo](https://bugs.gentoo.org/943656), are also considering turning them on by default. I don't think STK should be exempted from hardening efforts, especially considering its functionality includes communicating over the internet.

**Comment by v1993** [comment]
Still crashes for me on Git version as of commit 06fc57ea1d6f75d2803b57682091717fb1d0fca0 (built using `supertuxkart-git` in AUR); same error as before:

```
/usr/include/c++/15.2.1/bits/stl_bvector.h:1158: std::vector<bool, _Alloc>::reference std::vector<bool, _Alloc>::operator[](size_type) [with _Alloc = std::allocator<bool>; reference = std::vector<bool>::reference; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

Please note that the assert getting hit is not in the STK code but in the libstdc++; STK evidently tried to index an `std::vector<bool>` out-of-bounds.

**Comment by v1993** [comment]
Here's backtrace for the crash:

```
#0  0x00007ffff68aa0db in pthread_kill () from /usr/lib/libc.so.6
#1  0x00007ffff68447c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff682560d in abort () from /usr/lib/libc.so.6
#3  0x00007ffff6c9870f in std::__glibcxx_assert_fail (file=file@entry=0x55555570c538 "/usr/include/c++/15.2.1/bits/stl_bvector.h", line=line@entry=1158, 
    function=function@entry=0x555555702558 "std::vector<bool, _Alloc>::reference std::vector<bool, _Alloc>::operator[](size_type) [with _Alloc = std::allocator<bool>; reference = std::vector<bool>::reference; size_type = long unsigned int]", condition=condition@entry=0x5555556d0481 "__n < this->size()") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
#4  0x00005555557538e1 in std::vector<bool, std::allocator<bool> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/15.2.1/bits/stl_bvector.h:1158
#5  0x0000555555d5597b in CheckLine::isTriggered (this=0x555561cbbb60, old_pos=..., new_pos=..., kart_index=5) at /usr/src/debug/supertuxkart-git/stk-code/src/tracks/check_line.cpp:245
#6  0x0000555555d61a04 in CheckStructure::update (this=0x555561cbbb60, dt=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/tracks/check_structure.cpp:120
#7  0x0000555555ab8342 in CheckManager::update (this=0x555559b4fb40, dt=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/tracks/check_manager.cpp:185
#8  Track::update (this=<optimized out>, ticks=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/tracks/track.cpp:1745
#9  World::updateTrack (this=<optimized out>, ticks=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/modes/world.cpp:1251
#10 0x0000555555a963a8 in ThreeStrikesBattle::update (this=0x555559374ae0, ticks=1) at /usr/src/debug/supertuxkart-git/stk-code/src/modes/three_strikes_battle.cpp:360
#11 0x0000555555aa2ff7 in World::updateWorld (this=0x555559374ae0, ticks=1) at /usr/src/debug/supertuxkart-git/stk-code/src/modes/world.cpp:1051
#12 0x0000555555a6dc74 in MainLoop::updateRace (ticks=1, this=<optimized out>, fast_forward=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/main_loop.cpp:328
#13 MainLoop::run (this=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/main_loop.cpp:645
#14 0x0000555555a61fe0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/supertuxkart-git/stk-code/src/main.cpp:2632
```

**Comment by v1993** [comment]
P.S.: I don't think designating this as a "minor" issue is correct: this is UB being caught by hardening options enabled in major distros (including Flatpak runtime); it's **not** specific to debug builds.

**Comment by v1993** [comment]
Can confirm the arena now loads correctly with up to 16 AI karts; 17 causes placement to fail with

```
[fatal  ] Track: No start position for kart 17.
```

but that's apparently an issue with the arena and STK does nothing wrong. Thank you!

**Comment by v1993** [comment]
Not sure if it's worth opening another issue for, but doing three strikes battles on Moria's Race City Arena results in some really bizarre behaviors:

1. Multiple copies of a message when someone is eliminated (only sometimes)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cc4a919d-9a8c-4946-bdc3-fe7830678e22" />

2. List of karts and possibly the minimap can show less karts than there really are

3. Strangest of all, match ending seemingly at random before there's only one kart standing (or you get eliminated), resulting in a screen where you and a plenty of AI karts have the same time

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/12eaaf67-dbb2-4221-a6ad-19e4eeabf4cd" />

Also, swappers get activated incessantly - but that might be the natural result of a lot of karts with a lot of gift boxes.

**Comment by Alayan-stk-2** [comment]
> Not sure if it's worth opening another issue for, but doing three strikes battles on Moria's Race City Arena results in some really bizarre behaviors:

Better open another issue to keep things more organized.
